package
{
    public class Embedded
    {
        [Embed(source = './roms_chip8/15puzzle.c8', mimeType='application/octet-stream')]
        private static var _15puzzle_c8:Class;
        [Embed(source = './roms_chip8/15puzzle2.c8', mimeType='application/octet-stream')]
        private static var _15puzzle2_c8:Class;
        [Embed(source = './roms_chip8/Blinky.c8', mimeType='application/octet-stream')]
        private static var _Blinky_c8:Class;
        [Embed(source = './roms_chip8/Blitz.c8', mimeType='application/octet-stream')]
        private static var _Blitz_c8:Class;
        [Embed(source = './roms_chip8/Breakout.c8', mimeType='application/octet-stream')]
        private static var _Breakout_c8:Class;
        [Embed(source = './roms_chip8/Brix.c8', mimeType='application/octet-stream')]
        private static var _Brix_c8:Class;
        [Embed(source = './roms_chip8/C8pic.c8', mimeType='application/octet-stream')]
        private static var _C8pic_c8:Class;
        [Embed(source = './roms_chip8/Cave.c8', mimeType='application/octet-stream')]
        private static var _Cave_c8:Class;
        [Embed(source = './roms_chip8/Chip8Boot.c8', mimeType='application/octet-stream')]
        private static var _Chip8Boot_c8:Class;
        [Embed(source = './roms_chip8/Connect4.c8', mimeType='application/octet-stream')]
        private static var _Connect4_c8:Class;
        [Embed(source = './roms_chip8/Filter.c8', mimeType='application/octet-stream')]
        private static var _Filter_c8:Class;
        [Embed(source = './roms_chip8/Fishie.c8', mimeType='application/octet-stream')]
        private static var _Fishie_c8:Class;
        [Embed(source = './roms_chip8/Guess.c8', mimeType='application/octet-stream')]
        private static var _Guess_c8:Class;
        [Embed(source = './roms_chip8/Guess2.c8', mimeType='application/octet-stream')]
        private static var _Guess2_c8:Class;
        [Embed(source = './roms_chip8/Hidden.c8', mimeType='application/octet-stream')]
        private static var _Hidden_c8:Class;
        [Embed(source = './roms_chip8/IBM.c8', mimeType='application/octet-stream')]
        private static var _IBM_c8:Class;
        [Embed(source = './roms_chip8/Invaders.c8', mimeType='application/octet-stream')]
        private static var _Invaders_c8:Class;
        [Embed(source = './roms_chip8/Invaders2.c8', mimeType='application/octet-stream')]
        private static var _Invaders2_c8:Class;
        [Embed(source = './roms_chip8/Kaleid.c8', mimeType='application/octet-stream')]
        private static var _Kaleid_c8:Class;
        [Embed(source = './roms_chip8/Maze.c8', mimeType='application/octet-stream')]
        private static var _Maze_c8:Class;
        [Embed(source = './roms_chip8/Maze2.c8', mimeType='application/octet-stream')]
        private static var _Maze2_c8:Class;
        [Embed(source = './roms_chip8/Merlin.c8', mimeType='application/octet-stream')]
        private static var _Merlin_c8:Class;
        [Embed(source = './roms_chip8/Missile.c8', mimeType='application/octet-stream')]
        private static var _Missile_c8:Class;
        [Embed(source = './roms_chip8/Pong.c8', mimeType='application/octet-stream')]
        private static var _Pong_c8:Class;
        [Embed(source = './roms_chip8/Pong2.c8', mimeType='application/octet-stream')]
        private static var _Pong2_c8:Class;
        [Embed(source = './roms_chip8/Pong3.c8', mimeType='application/octet-stream')]
        private static var _Pong3_c8:Class;
        [Embed(source = './roms_chip8/Puzzle.c8', mimeType='application/octet-stream')]
        private static var _Puzzle_c8:Class;
        [Embed(source = './roms_chip8/Rocket.c8', mimeType='application/octet-stream')]
        private static var _Rocket_c8:Class;
        [Embed(source = './roms_chip8/Rocket2.c8', mimeType='application/octet-stream')]
        private static var _Rocket2_c8:Class;
        [Embed(source = './roms_chip8/Squash.c8', mimeType='application/octet-stream')]
        private static var _Squash_c8:Class;
        [Embed(source = './roms_chip8/Syzygy.c8', mimeType='application/octet-stream')]
        private static var _Syzygy_c8:Class;
        [Embed(source = './roms_chip8/Tank.c8', mimeType='application/octet-stream')]
        private static var _Tank_c8:Class;
        [Embed(source = './roms_chip8/Tapeworm.c8', mimeType='application/octet-stream')]
        private static var _Tapeworm_c8:Class;
        [Embed(source = './roms_chip8/Tetris.c8', mimeType='application/octet-stream')]
        private static var _Tetris_c8:Class;
        [Embed(source = './roms_chip8/Tictac.c8', mimeType='application/octet-stream')]
        private static var _Tictac_c8:Class;
        [Embed(source = './roms_chip8/UFO.c8', mimeType='application/octet-stream')]
        private static var _UFO_c8:Class;
        [Embed(source = './roms_chip8/VBrix.c8', mimeType='application/octet-stream')]
        private static var _VBrix_c8:Class;
        [Embed(source = './roms_chip8/Vers.c8', mimeType='application/octet-stream')]
        private static var _Vers_c8:Class;
        [Embed(source = './roms_chip8/Wall.c8', mimeType='application/octet-stream')]
        private static var _Wall_c8:Class;
        [Embed(source = './roms_chip8/Wipeoff.c8', mimeType='application/octet-stream')]
        private static var _Wipeoff_c8:Class;
        [Embed(source = './roms_chip8/X-Mirror.c8', mimeType='application/octet-stream')]
        private static var _XMirror_c8:Class;
        [Embed(source = './roms_schip/Alien.sc', mimeType='application/octet-stream')]
        private static var _Alien_sc:Class;
        [Embed(source = './roms_schip/Ant.sc', mimeType='application/octet-stream')]
        private static var _Ant_sc:Class;
        [Embed(source = './roms_schip/Blinky.sc', mimeType='application/octet-stream')]
        private static var _Blinky_sc:Class;
        [Embed(source = './roms_schip/BMPviewer.sc', mimeType='application/octet-stream')]
        private static var _BMPviewer_sc:Class;
        [Embed(source = './roms_schip/Car.sc', mimeType='application/octet-stream')]
        private static var _Car_sc:Class;
        [Embed(source = './roms_schip/Dragon1.sc', mimeType='application/octet-stream')]
        private static var _Dragon1_sc:Class;
        [Embed(source = './roms_schip/Dragon2.sc', mimeType='application/octet-stream')]
        private static var _Dragon2_sc:Class;
        [Embed(source = './roms_schip/Emutest.sc', mimeType='application/octet-stream')]
        private static var _Emutest_sc:Class;
        [Embed(source = './roms_schip/Field.sc', mimeType='application/octet-stream')]
        private static var _Field_sc:Class;
        [Embed(source = './roms_schip/Joust23.sc', mimeType='application/octet-stream')]
        private static var _Joust23_sc:Class;
        [Embed(source = './roms_schip/Maze.sc', mimeType='application/octet-stream')]
        private static var _Maze_sc:Class;
        [Embed(source = './roms_schip/Mines.sc', mimeType='application/octet-stream')]
        private static var _Mines_sc:Class;
        [Embed(source = './roms_schip/Piper.sc', mimeType='application/octet-stream')]
        private static var _Piper_sc:Class;
        [Embed(source = './roms_schip/Race.sc', mimeType='application/octet-stream')]
        private static var _Race_sc:Class;
        [Embed(source = './roms_schip/Spacefight.sc', mimeType='application/octet-stream')]
        private static var _Spacefight_sc:Class;
        [Embed(source = './roms_schip/Square.sc', mimeType='application/octet-stream')]
        private static var _Square_sc:Class;
        [Embed(source = './roms_schip/Test.sc', mimeType='application/octet-stream')]
        private static var _Test_sc:Class;
        [Embed(source = './roms_schip/UBoat.sc', mimeType='application/octet-stream')]
        private static var _UBoat_sc:Class;
        [Embed(source = './roms_schip/Worm3.sc', mimeType='application/octet-stream')]
        private static var _Worm3_sc:Class;

        public static var Internal:Object =
        {
        '15puzzle c8': new _15puzzle_c8(),
        '15puzzle2 c8': new _15puzzle2_c8(),
        'Blinky c8': new _Blinky_c8(),
        'Blitz c8': new _Blitz_c8(),
        'Breakout c8': new _Breakout_c8(),
        'Brix c8': new _Brix_c8(),
        'C8pic c8': new _C8pic_c8(),
        'Cave c8': new _Cave_c8(),
        'Chip8Boot c8': new _Chip8Boot_c8(),
        'Connect4 c8': new _Connect4_c8(),
        'Filter c8': new _Filter_c8(),
        'Fishie c8': new _Fishie_c8(),
        'Guess c8': new _Guess_c8(),
        'Guess2 c8': new _Guess2_c8(),
        'Hidden c8': new _Hidden_c8(),
        'IBM c8': new _IBM_c8(),
        'Invaders c8': new _Invaders_c8(),
        'Invaders2 c8': new _Invaders2_c8(),
        'Kaleid c8': new _Kaleid_c8(),
        'Maze c8': new _Maze_c8(),
        'Maze2 c8': new _Maze2_c8(),
        'Merlin c8': new _Merlin_c8(),
        'Missile c8': new _Missile_c8(),
        'Pong c8': new _Pong_c8(),
        'Pong2 c8': new _Pong2_c8(),
        'Pong3 c8': new _Pong3_c8(),
        'Puzzle c8': new _Puzzle_c8(),
        'Rocket c8': new _Rocket_c8(),
        'Rocket2 c8': new _Rocket2_c8(),
        'Squash c8': new _Squash_c8(),
        'Syzygy c8': new _Syzygy_c8(),
        'Tank c8': new _Tank_c8(),
        'Tapeworm c8': new _Tapeworm_c8(),
        'Tetris c8': new _Tetris_c8(),
        'Tictac c8': new _Tictac_c8(),
        'UFO c8': new _UFO_c8(),
        'VBrix c8': new _VBrix_c8(),
        'Vers c8': new _Vers_c8(),
        'Wall c8': new _Wall_c8(),
        'Wipeoff c8': new _Wipeoff_c8(),
        'XMirror c8': new _XMirror_c8(),
        'Alien sc': new _Alien_sc(),
        'Ant sc': new _Ant_sc(),
        'Blinky sc': new _Blinky_sc(),
        'BMPviewer sc': new _BMPviewer_sc(),
        'Car sc': new _Car_sc(),
        'Dragon1 sc': new _Dragon1_sc(),
        'Dragon2 sc': new _Dragon2_sc(),
        'Emutest sc': new _Emutest_sc(),
        'Field sc': new _Field_sc(),
        'Joust23 sc': new _Joust23_sc(),
        'Maze sc': new _Maze_sc(),
        'Mines sc': new _Mines_sc(),
        'Piper sc': new _Piper_sc(),
        'Race sc': new _Race_sc(),
        'Spacefight sc': new _Spacefight_sc(),
        'Square sc': new _Square_sc(),
        'Test sc': new _Test_sc(),
        'UBoat sc': new _UBoat_sc(),
        'Worm3 sc': new _Worm3_sc()
        }
    }
}
